apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - sources.yaml
  - gateway-api-crds.yaml
  - cilium.yaml
  - cilium-bgp.yaml
  - cert-manager.yaml
  - external-secrets.yaml
  - 1password-connect.yaml
  - cluster-secret-store.yaml
  - kubelet-serving-cert-approver.yaml
  - metrics-server.yaml
  - external-dns.yaml
  - networking.yaml
  - tns-csi.yaml
