apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: services-bgp
  namespace: metallb
spec:
  addresses:
  - 10.0.50.100-10.0.50.150
---
apiVersion: metallb.io/v1beta2
kind: BGPPeer
metadata:
  name: opnsense
  namespace: metallb
spec:
  myASN: 64513
  peerASN: 64512
  peerAddress: 10.0.40.1
---
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: services-bgp
  namespace: metallb
spec:
  ipAddressPools:
  - services-bgp