apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cilium.yaml
  - jetstack.yaml
  - external-secrets.yaml
  - 1password.yaml
  - metrics-server.yaml
  - kubelet-serving-cert-approver.yaml
  - external-dns.yaml
